from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import hilbert
from scipy.fft import set_workers
from enum import Enum
import json
import os
from strip_tools import NMRData, ResolutionEnhance, ProcessMode, Plotter
from strip_params import SimParams, PlotParams
    
curr_dir = Path(__file__).resolve().parents[0]

def here(fileName):
    return os.path.join(curr_dir, fileName)

simOverrides = dict(
    resolutionEnhance = ResolutionEnhance.Early,
    loops = 15,
    dt1 = 0.032,
    dt2 = 0.004,
    t1Size = 1024,
    t2Size = 4096,
    gaussianBroaden1 = 0.8,
    expBroaden1 = -0.2,
    gaussianBroaden2 = 0.8,
    expBroaden2 = -0.2,
    noiseLevel = 0.0,
    signalBox = None,
    noiseBox = None)

plotOverrides = dict(
    doZoom = True,
    zoom = (1538, 5741, 1900, 6351),
    plotLabelOffset = (5, 330),
    labelSize = 40
)

AMPLITUDE_MODULATED_FILE = here("amplitude_modulated.npy")
PHASE_MODULATED_FILE = here("phase_modulated.npy")
RANDOM_PEAKS_FILENAME = here("random_peaks.json")

class NMRDataMultiplePeaks(NMRData):
    def __init__(self, simParams):
        self.simParams = simParams
        self.inventDataMulti()

    def inventDataMulti(self):
        window1, window2 = self.create_windows() 
        
        if self.simParams.processMode == ProcessMode.AmplitudeModulated:
            binary_file = AMPLITUDE_MODULATED_FILE
        else:
            binary_file = PHASE_MODULATED_FILE 
        
        if os.path.exists(binary_file):
            self.spectrum = np.load(binary_file)
        else:
            self.spectrum = np.zeros((self.simParams.t1Size*2, self.simParams.t2Size*2), dtype=complex)
            # get peaks from random peaks generated by random_peaks.py
            with open(RANDOM_PEAKS_FILENAME, 'r') as f:
                peaks = json.load(f)
            for peak in peaks:
                intensity = peak['intensity']
                freq1 = peak['y']
                freq2 = peak['x']
                relaxation = peak['relaxation']
                if self.simParams.processMode == ProcessMode.AmplitudeModulated:
                    spectrum = self.get_amplitude_modulated_spectrum(intensity, freq1, freq2, relaxation, window1, window2)
                else:
                    spectrum = self.get_phase_modulated_spectrum(intensity, freq1, freq2, relaxation, window1, window2)
                print('Added peak number %d' % peak['id'])
                self.spectrum = self.spectrum + spectrum
                
            np.save(binary_file, self.spectrum)
                
        shape = self.spectrum.shape

scenarios = [ ProcessMode.AmplitudeModulated,
              ProcessMode.STRIP,
              ProcessMode.AbsoluteValue ]


def process():
    for scenario in scenarios:
        plt.rcParams["figure.figsize"] = (18, 6)
        simOverrides['processMode'] = scenario
        plotOverrides['plotLabel'] = scenario.label
        plotOverrides['plotFileName'] = here("Figure_" + scenario.label + ".png")
        nmrData = NMRDataMultiplePeaks(simParams=SimParams(**simOverrides))
        plotter = Plotter(plotParams=PlotParams(**plotOverrides))
        nmrData.simulate(plotter)
        
def main():
    process()

if __name__ == '__main__':
    main()